version: "3"

services:
  app:
    image: registry.devacceso.com/${IMAGENAME}:${CI_PIPELINE_ID}
    # image: registry.devacceso.com/treausy-app:5151
    build: .
    # restart: always
    ports:
      - "${PORTSALIDA}:${PORTDOCKER}"
      # - "2121:2121"
    command: bash -c "npm run start:${ENVDEPLOY}"
    # command: bash -c "npm run start:local"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.4.239:12201"
        tag: treasury-app
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.labels.name == ${NODO}
        # - node.labels.name == swarm-node
